language: go
go:
- 1.6
- release
- tip
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master
addons:
  ssh_known_hosts: paged.me
install:
  - go get
  - go install
  - go build
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
before_install:
- openssl aes-256-cbc -K $encrypted_511bf3d7a094_key -iv $encrypted_511bf3d7a094_iv
  -in deploy_rsa.enc -out deploy_rsa -d
